language: rust

env:
  global:
    - secure: CT40Kl5Q5K5L+4NBeh7M1O2pbx4ozX4C/6PIVJqIoV/czhi358ZQSpWl9PzIDkCPI5fjn/CA6/2q89R7nRh9e5JkRg5GoqpV+xgEIijRsKSBLhot3elWli++QGsmAzCgMmbOpYVJUGQVVaLmBTwT2bMpZpegseaB4M5wrdwtVYk=

script:
  - cargo build --verbose
  - cargo test --verbose
  - cd macros && cargo test --verbose && cd ..
  - cargo doc --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master
