language: rust
sudo: false

env:
  global:
    - secure: wTFLm1V7jDJyd8ajUnQ0aZ14BQmpNlvybz7KaqIT4InmmQSKRq6gRPdE2L96lhv+7wPXmhxk0SoaEY/6tt1dS0rbsnrlmJgW0sBQAxpm5iJu1E7cF5QXATww7pUo79ax2ydxaXcwiaUC/F5u599MGx6ajMxumc+oeXaGVo+VAmo=

script:
  - cargo build --features macros --verbose
  - cargo test --features macros --verbose
  - cd macros && cargo test --verbose && cd ..
  - cargo doc --features macros --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master
